### ISSUE TITLE
Can we simplify the error parsing feature?

### ISSUE THREAD

**Issue by simondotm** [simondotm/beeb-vsc#101]
Clearly, some folks have some exotic workspace setups for their beeb projects! 😂 

If it is at all possible for the extension to determine entry points from any beebasm command lines in the `tasks.json` and then somehow automatically figure out include dependencies from that root without users having to manually manage it, that would be great.

Let's discuss.

_Originally posted by @simondotm in https://github.com/simondotm/beeb-vsc/issues/99#issuecomment-2021304354_

**Comment by tommy9** [comment]
For safety, should probably be able to scan both the older 0.1.0 schema and new 2.0.0 schema, in case some people created updated tasks.json files themselves.

**Comment by simondotm** [comment]
_Originally posted by @tommy9 in https://github.com/simondotm/beeb-vsc/issues/99#issuecomment-2021352383_
            
> I agree that picking up the entry points from the existing tasks.json would be a really nice thing to do automatically. I had avoided it earlier because of the number of projects relying on exotic batch scripts or make files but that isn't a reason not to add this quality of life feature for the many standard projects that are out there.

Ah yes, I remember the other stardot thread now,  the folks with the makefiles and batch files, yes, that makes things spicier.

Still, I think if at least we could implement the automation of parsing the hierarchy of includes somehow, then `settings.json` content could be just a list of entry files rather than _all_ included files perhaps?
