### ISSUE TITLE
v0.2.3 release

### ISSUE THREAD

**Issue by tommy9** [simondotm/beeb-vsc#114]
Hi @simondotm 

I was thinking to try the release process, just some minor improvements since the last version so hopefully low risk!

Just wanted to check in if there was any pending change you wanted to include?

**Comment by simondotm** [comment]
Hey @tommy9 
Not from my side, you are going great with your updates though, I've been getting the notifications etc.
So go for it, release away! Thanks for your contributions 👍

**Comment by tommy9** [comment]
It all went very smoothly thanks to your release process guide, thanks for making that!

I'll keep an eye out in the marketplace for when it gets refreshed so I can test the production release too. 

🚀

**Comment by simondotm** [comment]
Great stuff @tommy9 !
