### ISSUE TITLE
Wrong comment character

### ISSUE THREAD

**Issue by mspeculatrix** [simondotm/beeb-vsc#16]
When I press Cmd-/ (on the Mac) it seems to select block comments usng /* and */ whereas I need ; or \ in BeebAsm. Is there any way to change this behaviour?

**Comment by tommy9** [comment]
I managed to change this in my copy. You can edit the extension configuration file found on the Mac in ~/.vscode/extensions/simondotm.beeb-vsc-0.0.6 as beeb-vsc.configuration.json

Change the top section to be 
```json
    "comments": {
        "lineComment": ";"
      },
```

This removes the blockComment section and reduces the lineComment section to just a single value as vscode doesn't support multiple line comment items according to [this issue](https://github.com/Microsoft/vscode/issues/64659). After restarting vscode, Cmd-/ should work as expected.
