### ISSUE TITLE
Add CI

### ISSUE THREAD

**Issue by simondotm** [simondotm/beeb-vsc#21]
Add automation for:
* Pull requests 
* Publishing releases to the extensions marketplace

**Comment by simondotm** [comment]
Implemented in #20 
Had to fiddle a bit with the publish CI but got there in the end.

Publish process is as follows:
1. The `package.json` version must be updated & pushed to remote
2. Create a GitHub release
3. For the release, add a tag matching the package version (CI will check for this) prefixed with a v - eg. `v0.1.0`
4. Name the release the same as the tag eg. `v0.1.0`
5. Auto generate the release notes
6. Press Publish
7. CI will run, it will verify the release tag matches the package, build the extension, and publish it to marketplace

**Comment by simondotm** [comment]
@tommy9 
So `v0.1.0` is now live as the official latest version! 🎉 
It will be much easier to publish updates from here. 👍 
Thanks very much for your hard work on moving this plugin forward. Great stuff.

**Comment by tommy9** [comment]
Great news! Thanks for the invitation too 😄
