### ISSUE TITLE
Code style

### ISSUE THREAD

**Issue by simondotm** [simondotm/beeb-vsc#34]
Hi @tommy9 
I wondered if you have any strong feelings about code formats?
I like prettier myself, it keeps things simple & consistent, and automates styling.
Usually I go for the default config - spaces over tabs, 2-space indents. 
And, controversially, I usually strip semi-colons since they are just noise in this day and age.

I will go ahead and add prettier unless any objections or other preferences. 👍

**Comment by tommy9** [comment]
Hi @simondotm 
I don't have any strong feelings as I'm very new to TypeScript/JavaScript. Most of my experience has been with basic style languages like VBA or Python. I've always mocked c-style languages for their need to end lines with a semi-colon, so very happy that this can go! Happy to go with your suggestion. 👍

**Comment by simondotm** [comment]
Ok this is now done. 
Using default prettier options, ftw.
Eslint in vscode should automatically style on save now. No drama.
If not, check vscode 'format on save' settings, and use eslint as formatter
