### ISSUE TITLE
v0.1.2 Release and beyond 🚀 

### ISSUE THREAD

**Issue by simondotm** [simondotm/beeb-vsc#41]
@tommy9 
Great news! The v0.1.2 release is now published and has your fixes. 👍 Thanks for those, nice work.

Next steps, I'm going to merge this big PR I have for properly adding JsBeeb.

When you next take the latest, and debug the extension locally, you can try it out by right clicking an SSD/DSD file or from command palette menu `> Beeb VSC: Open in Emulator`

This feature is currently disabled for prod builds, so we can still make interim releases from master branch if we're fixing other things in the meantime. 

Oh and, remember to `npm install` after pulling latest!

**Comment by tommy9** [comment]
This is great! It worked (after I switched to the right version of npm). 

One quick observation - it isn't auto-booting the disk image. Ideally something the user could configure but maybe default to booting is nice to have.

**Comment by simondotm** [comment]
> but maybe default to booting is nice to have

Absolutely, there's a ton of possibilities now. 😄 
I just wanted to get the initial working version merge so we can iterate feature incrementally now. If you have ideas, just create a new issue for them.

Next up for me will be to get the toolbar working properly with start/stop, reboot, disc selection controls.
Then maybe audio on/off.

Plus I need to fix the info bar at the bottom to show coords etc.

Since it's all webview stuff, its pretty easy to make new UI. Could have a disc layout preview, hex dumps, graphics memory renderers, cpu state etc. 

One step at a time though 😆

**Comment by simondotm** [comment]
@tommy9 I fixed the autoboot thing! 👍 
Closing this one. Will open a v0.1.3 release topic
