### ISSUE TITLE
File watchers

### ISSUE THREAD

**Issue by simondotm** [simondotm/beeb-vsc#80]
Hi @tommy9 
Just a heads up that in PR #77 I added some file watching capabilities. Its mainly for detecting the presence of `dsd` or `ssd` files in the workspace, but maybe that could also come in useful for detecting changes to `.asm` / `.s` / `.6502` files too? eg. for optimizing symbol processing/listing possible entry point files etc.
Food for thought anyway 👍 

https://github.com/simondotm/beeb-vsc/blob/master/src/client/panels/emulator-panel.ts#L74-L108

**Comment by tommy9** [comment]
Thanks, I'll look at how to trigger a re-parse if the settings.json file is updated. We should be notified of changes to the code files (assuming that they are edited in vscode that is) but would not notice any changes to the settings file immediately.
