### ISSUE TITLE
v0.2.0 release

### ISSUE THREAD

**Issue by simondotm** [simondotm/beeb-vsc#91]
Hi @tommy9,
I've just about finished the jsbeeb emulator feature now.
So we can think about the next release now (going to be v0.2.0)

Do you have any pending things you'd like to get into the next release?

**Comment by tommy9** [comment]
Hi @simondotm
Nothing urgent. I've been looking at some other extensions about debugging but mostly getting confused! I'll log some ideas as new issues but not worth waiting for probably.

**Comment by simondotm** [comment]
Ok great stuff. The new features you've added are awesome! Thanks for all your help

**Comment by simondotm** [comment]
@tommy9 v0.2.0 is published! 🎉 👍
