### ISSUE TITLE
Parse issues when settings.json not set up

### ISSUE THREAD

**Issue by tommy9** [simondotm/beeb-vsc#99]
There have been reports of parsing issues (numerous lines of code underlined and reporting problems).

This seems to be caused by not having the targets defined. Previously this was not causing problems because we would quietly fail. My recent changes to try and find the roots is probably failing in some cases then it parses from the wrong starting point, leading to 'symbol not defined' errors and more.

I will prepare a fix to notify the user that they should create a new target (or targets) and not try parsing as much if we don't find the target information.

Ref: https://stardot.org.uk/forums/viewtopic.php?p=421019

**Comment by tommy9** [comment]
Should be addressed by #100 
@simondotm would it be possible to do a new release with this fix please? At least 3 people have reported issues now.

**Comment by simondotm** [comment]
@tommy9 great work getting a fix together so quickly! Thanks

I will make a new release just now.

**Comment by tommy9** [comment]
Wonderful, thank you for the quick release!

I agree that picking up the entry points from the existing tasks.json would be a really nice thing to do automatically. I had avoided it earlier because of the number of projects relying on exotic batch scripts or make files but that isn't a reason not to add this quality of life feature for the many standard projects that are out there.

**Comment by simondotm** [comment]
v0.2.2 is now live. 🚀

**Comment by simondotm** [comment]
@tommy9 just FYI, I added instructions for how to do new releases. As a collaborator I believe you should be able to do this also if its urgent and I'm not available for any reason.

It's all taken care of by the CI. 🚀 
https://github.com/simondotm/beeb-vsc/blob/master/docs/release-process.md
